config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: postgres
      host: host.docker.internal
      pass: password
      port: 5432
      schema: public
      threads: 8
      type: postgres
      user: demo_user
  target: prod
