FROM python:3.11-slim

WORKDIR /opt/dagster/app

COPY orchestrator /opt/dagster/app/orchestrator
COPY dbt_project /opt/dagster/app/dbt_project
COPY setup.py setup.cfg requirements_user_code.txt /opt/dagster/app/

RUN pip install -r /opt/dagster/app/requirements_user_code.txt

EXPOSE 4000

CMD ["dagster", "api", "grpc", "--module-name", "orchestrator", "--host", "0.0.0.0", "--port", "4000"]
