configuration:
  namespace_definition: destination
  namespace_format: ${SOURCE_NAMESPACE}
  prefix: ''
  resource_requirements:
    cpu_limit: ''
    cpu_request: ''
    memory_limit: ''
    memory_request: ''
  status: active
  sync_catalog:
    streams:
    - config:
        alias_name: users
        cursor_field: []
        destination_sync_mode: append
        primary_key: []
        selected: true
        sync_mode: full_refresh
      stream:
        default_cursor_field: []
        json_schema:
          $schema: http://json-schema.org/draft-07/schema#
          properties:
            address:
              type: string
            birthdate:
              format: date
              type: string
            blood_group:
              type: string
            company:
              type: string
            created_at:
              airbyte_type: timestamp_without_timezone
              format: date-time
              type: string
            current_location:
              type: array
            id:
              type: number
            job:
              type: string
            mail:
              type: string
            name:
              type: string
            residence:
              type: string
            sex:
              type: string
            ssn:
              type: string
            updated_at:
              airbyte_type: timestamp_without_timezone
              format: date-time
              type: string
            username:
              type: string
            website:
              type: array
          type: object
        name: users
        namespace: public
        source_defined_cursor: true
        source_defined_primary_key: []
        supported_sync_modes:
        - full_refresh
        - incremental
definition_type: connection
resource_name: demo_connection
source_configuration_path: sources/fake_users/configuration.yaml
destination_configuration_path: destinations/postgres_destination/configuration.yaml
